name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install g++ -y
        g++ --version

    - name: Build C++ code
      run: g++ -o test main.cpp  

    - name: Run C++ tests
      run: ./test  

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./build/test_results/  
